version: '3.8'
services:

  frontend:
    build: ../frontend
    container_name: foodgram_frontend
    restart: no
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.24.0
    container_name: foodgram_gateway
    restart: always
    ports:
      - 8007:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
